import type { Metadata } from "next";
import { Fira_Sans as FontFiraSans } from "next/font/google";
import "./globals.css";

import { cn } from "@/lib/utils";

const fontFiraSans = FontFiraSans({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["100", "200", "300", "400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontFiraSans.variable
        )}
      >
        {children}
      </body>
    </html>
  );
}
